### ISSUE TITLE
Create placeholder page

### ISSUE THREAD

**Issue by hunvreus** [Wiredcraft/twig#2]
After you're done with #1, you should try and create a simple GitHub pages on this repo to demo how to use the icon set.

I've already created a `gh-pages` branch; once you push content to it, we should have the page available at http://wiredcraft.com/twig since we host http://wiredcraft.com at `Wiredcraft/wiredcraft.github.io` (I can explain more in details if you ask me, it's one of the awesome things with GitHub pages).

**Comment by hunvreus** [comment]
Here is an example of a fully functioning (and complex-ish) Jekyll site:

https://www.dropbox.com/s/9lnxxmdj9zamooq/wiredcraft.github.io-master.zip?dl=0

**Comment by hunvreus** [comment]
You can read the README.md file, although keep in mind a few things:
- I use Bower & Gulp for dependencies and building CSS from SASS, as well as `npm` for the SASS and Gulp dependencies,
- I have a lot of custom collections (`_work`, `_team`...) which you won't need
- I use [eggshell](http://github.com/Wiredcraft/eggshell), a lightweight SASS module we use as a boilerplate for our styling,
- Look at the `_js` folder, that's where i have my custom jQuery scripts (for example `_js/menu.js` which helps me handle the collapsing menu on mobile)

Anything else, ask. You'll likely build just a single page anyway.

**Comment by jasongroenewald** [comment]
![round2](https://cloud.githubusercontent.com/assets/5840259/9623258/6d9a7ab6-513e-11e5-872b-937a19ef4544.jpg)

*Logo, download button and GitHub logo in header
*Search bar with clear icon, also added in a category filter, might be overkill and more useful when there are more icons
*I've added a copy link to the icons on hover
*The download section, I've made a bar with a button, having it a large section without copy just felt a lil off
*How to use is a standard section with a bit of text
*Then simple footer with copyright, links and a logo

**Comment by hunvreus** [comment]
Yep, more or less. A few comments:
1. I now thing using the Wiredcraft styling wouldn't be that good.
2. I would try to see if we can avoid separating the header from the rest of the hero (aka the search bar + icons + header just have the same background color).
3. I'd center the download button in the mid section (we can make it attractice) and add a "Fork on GitHub" button next to it.
4. I'd make the search bar nice but somehow integrated into the background (we don't want it to be a big white block across the page, it's just a nice to have since we only have a few dozens icons).
