### ISSUE TITLE
Wireframe for the page

### ISSUE THREAD

**Issue by hunvreus** [Wiredcraft/twig#3]
Let's discuss here the overall content, layout and design for the landing page of the twig icon set. You should already have some ideas, feel free to share the link for the pinterest board you were preparing and take pictures of doodles you may have come up with (I do that all the time). Once (if?) we have more polished mockups, we can also upload it in the comments.

**Comment by jasongroenewald** [comment]
![twig-landing-page-initial](https://cloud.githubusercontent.com/assets/5840259/9569042/bf6dbf84-4f5d-11e5-8009-9b864a446cfb.jpg)

First draft idea, rough direction

**Comment by hunvreus** [comment]
Good, however we should try and first list the features we want to put and think about the information architecture. Where's your pinterest?

**Comment by jasongroenewald** [comment]
Morning

I'll start compiling a list of content, just wanted a basic draft of
layout. Added Pinterest list on Friday to the Slack group?

www.pinterest.com/groenewaldjas/inspiration-icons/

Thanks
Jason

**Comment by jasongroenewald** [comment]
My initial thoughts on 
**Features**
_I think the biggest draw card for this would be to use a CDN to host the associated styles and generated fonts. The feature we can push with that could be that it is easy to install, plug-and-play etc.
*Option to download SVGs, EPS etc or to download the library (Fonts and stylesheet) to use locally. Good to push this feature to show flexibility on the icon set?
*Semantic markup for ease of use. I've prepended the classes with *_'tw'*\* to avoid potential conflicts with other CSS style. We could also potentially have UNICODE fallbacks for some of the icons? 
*Retina ready / fully scalable icons, SVGS and their benefits is a great feature...
*Icon sizes and colors can also be easier controlled with existing size classes, you could also add your own sizes if need be etc.

**Comment by hunvreus** [comment]
Let's take this to Hackpad: https://hackpad.com/Twig-icon-set-WZtV10TE8ZX

**Comment by jasongroenewald** [comment]
![twig-hero](https://cloud.githubusercontent.com/assets/5840259/9642904/17d4001c-51bf-11e5-8063-e6aeb27a56cb.png)

Internet issues, so while I sort those out and polish the page, I've done a quick mockup of hero section for general direction
